#ifndef COMMON_H
#define COMMON_H

/*
 * Included at the top of every splat-generated C file (splat's
 * `generated_c_preamble` option, which defaults to this filename).
 *
 * include_asm.h is generated by splat and defines INCLUDE_ASM /
 * INCLUDE_RODATA, plus the .include of include/labels.inc that the
 * pulled-in assembly depends on. It also stubs both macros out under
 * M2CTX and PERMUTER, which is what lets m2c and decomp-permuter parse
 * a partially decompiled file.
 */
#include "include_asm.h"

/*
 * Sized types. gcc 2.9 predates <stdint.h>, and the EE is ILP32 with a
 * 64-bit long long.
 */
typedef signed char        s8;
typedef unsigned char      u8;
typedef signed short       s16;
typedef unsigned short     u16;
typedef signed int         s32;
typedef unsigned int       u32;
typedef signed long long   s64;
typedef unsigned long long u64;
typedef float              f32;
typedef double             f64;

/*
 * The 128-bit type the EE's MMI instructions operate on. gcc 2.9 for the
 * R5900 provides this; it shows up in any code touching sceVu0* maths.
 */
#ifndef u128
typedef unsigned int u128 __attribute__((mode(TI)));
#endif

#endif /* COMMON_H */