#!/usr/bin/env python3
import sys
from pathlib import Path

if len(sys.argv) != 3:
    sys.exit("usage: bin2s.py <input.bin> <output.s>")

src, dst = Path(sys.argv[1]), Path(sys.argv[2])
dst.parent.mkdir(parents=True, exist_ok=True)
dst.write_text(
    "/* Generated by tools/bin2s.py -- do not edit */\n"
    ".section .data\n"
    f'.incbin "{src.as_posix()}"\n')