#!/usr/bin/env python3
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

CODE_TYPES = {"c", "cpp", "asm", "hasm"}
SUBSEG_RE = re.compile(
    r"^(\s*-\s*\[\s*)(0x[0-9A-Fa-f]+)(\s*,\s*)(\w+)(\s*,\s*)([\w$.]+)(\s*\].*)$")
OPTION_RE = re.compile(r"^(\s*)(\w+):(\s*)(.*)$")

def overrides(args):
    return {
        "asm_path": args.asm_path,
        "nonmatchings_path": f"{args.asm_path}/nonmatchings",
        "ld_script_path": args.ld_script,
        "undefined_syms_auto_path": args.undef_syms,
        "undefined_funcs_auto_path": args.undef_funcs,
    }

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("yaml", type=Path)
    ap.add_argument("-o", "--out", type=Path,
                    help="default: <input>.target.yaml alongside the input")
    ap.add_argument("--asm-path", default="asm/target")
    ap.add_argument("--ld-script", default="config/generated.target.ld")
    ap.add_argument("--undef-syms",
                    default="config/undefined_syms_auto.target.txt")
    ap.add_argument("--undef-funcs",
                    default="config/undefined_funcs_auto.target.txt")
    args = ap.parse_args()

    src = args.yaml if args.yaml.is_absolute() else ROOT / args.yaml
    if not src.is_file():
        sys.exit(f"{src}: not found")

    out = args.out
    if out is None:
        out = src.with_suffix("")
        out = out.with_name(out.name + ".target.yaml")
    if not out.is_absolute():
        out = ROOT / out

    over = overrides(args)
    lines = src.read_text().splitlines()
    result = []
    converted = 0
    seen_opts = set()
    in_options = False

    for line in lines:
        m = SUBSEG_RE.match(line)
        if m and m.group(4) in CODE_TYPES:
            if m.group(4) != "asm":
                converted += 1
            result.append(f"{m.group(1)}{m.group(2)}{m.group(3)}asm"
                          f"{m.group(5)}{m.group(6)}{m.group(7)}")
            continue

        om = OPTION_RE.match(line)
        if om and om.group(1) == "  " and not line.lstrip().startswith("-"):
            key = om.group(2)
            in_options = True
            if key in over:
                seen_opts.add(key)
                result.append(f"  {key}: {over[key]}")
                continue
            if key == "src_path":
                continue        # nothing is generated into src/
        elif in_options and line.strip().startswith("segments:"):
            for key, val in over.items():
                if key not in seen_opts:
                    result.append(f"  {key}: {val}")
            in_options = False

        result.append(line)

    header = [
        "# GENERATED by tools/gen_target_yaml.py -- do not edit.",
        "#",
        "# Every code subsegment is `asm` here, so splat disassembles the",
        "# original in full no matter what src/ contains. This is the",
        "# reference side for objdiff; the hand-written side comes from",
        f"# {src.name}.",
        "",
    ]
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(header + result) + "\n")

    print(f"wrote {out}")
    print(f"  {converted} code subsegment(s) converted to asm")
    for k, v in over.items():
        print(f"  {k}: {v}")
    if converted == 0:
        print("  WARNING: nothing converted -- check the subsegment format")
    return 0

if __name__ == "__main__":
    sys.exit(main())
