#!/usr/bin/env python3
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

OUT = ROOT / "include" / "functions.h"
ASM = ROOT / "asm" / "nonmatchings"
UNDEF = ROOT / "config" / "undefined_funcs_auto.txt"

FUNC_RE = re.compile(r"\bfunc_[0-9A-Fa-f]{8}\b")
NAME_RE = re.compile(r"^func_([0-9A-Fa-f]{8})$")

DECL_RE = re.compile(r"^[^/].*?\b(func_[0-9A-Fa-f]{8})\s*\(")

HEADER = """\
#ifndef FUNCTIONS_H
#define FUNCTIONS_H

/*
 * Generated by tools/gen_protos.py -- but SAFE TO EDIT.
 */

#ifdef __cplusplus
extern "C" {
#endif

"""

FOOTER = """
#ifdef __cplusplus
}
#endif

#endif /* FUNCTIONS_H */
"""

def discover():
    names = set()

    if ASM.is_dir():
        for p in ASM.rglob("func_*.s"):
            if NAME_RE.match(p.stem):
                names.add(p.stem)

    if UNDEF.is_file():
        for line in UNDEF.read_text(errors="replace").splitlines():
            line = line.split("//", 1)[0]
            names.update(FUNC_RE.findall(line))

    return sorted(names)

def existing(path: Path):
    if not path.is_file():
        return [], {}
    body = []
    decls = {}
    text = path.read_text(errors="replace")

    start = text.find('extern "C" {')
    if start != -1:
        start = text.find("\n", start) + 1
        end = text.find("#ifdef __cplusplus", start)
        if end == -1:
            end = len(text)
        text = text[start:end]

    for line in text.splitlines():
        stripped = line.strip()
        m = DECL_RE.match(stripped)
        if m:
            decls[m.group(1)] = line.rstrip()
            body.append(line.rstrip())
        elif stripped.startswith("/*") or stripped.startswith("//"):
            if line.rstrip() not in body:
                body.append(line.rstrip())
    return body, decls

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report what would be added, write nothing")
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args()

    names = discover()
    if not names:
        sys.exit("no func_* symbols found -- run configure.py --split first")

    body, decls = existing(args.out)
    missing = [n for n in names if n not in decls]

    print(f"{len(names)} function(s) known, {len(decls)} already declared, "
          f"{len(missing)} to add")

    if not missing:
        if not args.check:
            print(f"{args.out} is up to date")
        return 0

    if args.check:
        for n in missing[:20]:
            print(f"  + {n}")
        if len(missing) > 20:
            print(f"  ... and {len(missing) - 20} more")
        return 1

    lines = list(body)
    if lines and lines[-1].strip():
        lines.append("")
    lines.append("/* --- appended by tools/gen_protos.py --- */")
    for n in missing:
        lines.append(f"void {n}(void);")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(HEADER + "\n".join(lines) + "\n" + FOOTER)
    print(f"wrote {args.out}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
