#!/usr/bin/env python3
import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
COMPILER_ID = os.environ.get("COMPILER_ID", "ee-gcc2.96")

EXTERN_C = re.compile(r'extern\s*"C"\s*')

def strip_extern_c(text):
    out, i, n = [], 0, len(text)
    while True:
        m = EXTERN_C.search(text, i)
        if not m:
            out.append(text[i:])
            return "".join(out)
        out.append(text[i:m.start()])
        j = m.end()
        if j < n and text[j] == "{":
            depth, k = 0, j
            while k < n:
                if text[k] == "{":
                    depth += 1
                elif text[k] == "}":
                    depth -= 1
                    if depth == 0:
                        break
                k += 1
            out.append(text[j + 1:k])
            i = min(k + 1, n)
        else:
            i = j

COMPILE_SH = """\
#!/bin/bash
# Generated by tools/mkpermuter.py
set -e

CPP={cpp}
CC1={cc1}
AS={as_}

CPP_FLAGS=({cpp_flags})
CC1_FLAGS=({cc1_flags})
AS_FLAGS=({as_flags})

INPUT=""
OUTPUT=""
while [ $# -gt 0 ]; do
    case "$1" in
        -o) OUTPUT="$2"; shift 2 ;;
        *)  INPUT="$1"; shift ;;
    esac
done

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

"$CPP" "${{CPP_FLAGS[@]}}" "$INPUT" "$TMP/out.i"
"$CC1" "${{CC1_FLAGS[@]}}" "$TMP/out.i" -o "$TMP/out.s"
"$AS" "${{AS_FLAGS[@]}}" -o "$OUTPUT" "$TMP/out.s"
"""

def find(stem):
    base = ROOT / "tools" / "compilers" / COMPILER_ID
    for pat in (stem, f"{stem}.exe"):
        hits = sorted(base.rglob(pat))
        if hits:
            return hits[0]
    return None

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("source", type=Path, help="e.g. src/menu_file.c")
    ap.add_argument("func", help="e.g. func_001C0E34")
    ap.add_argument("--unit", help="target unit name (default: source stem)")
    ap.add_argument("--out", type=Path, default=ROOT / "nonmatchings")
    args = ap.parse_args()

    src = args.source if args.source.is_absolute() else ROOT / args.source
    if not src.is_file():
        sys.exit(f"{src}: not found")

    unit = args.unit or src.stem
    target_o = ROOT / "build" / "target" / f"{unit}.o"
    if not target_o.is_file():
        sys.exit(f"{target_o} missing -- run: ninja -k 0 build/target/{unit}.o")

    nm = shutil.which("mips64r5900el-ps2-elf-nm")
    if nm:
        out = subprocess.run([nm, str(target_o)], capture_output=True,
                             text=True).stdout
        if args.func not in out:
            sys.exit(f"{args.func} is not in {target_o}.\n"
                     f"Check that asm/target/{unit}.s contains it.")

    cpp, cc1, as_ = find("ee-cpp"), find("cc1"), "mips64r5900el-ps2-elf-as"
    if cpp is None or cc1 is None:
        sys.exit(f"cpp/cc1 not found under tools/compilers/{COMPILER_ID}")

    d = args.out / args.func
    d.mkdir(parents=True, exist_ok=True)

    r = subprocess.run(
        [str(cpp), "-D__GNUC__=2",
         "-Iinclude", "-Iinclude/sdk", str(src.relative_to(ROOT))],
        cwd=ROOT, capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write(r.stderr)
        sys.exit("cpp failed")
    body = strip_extern_c(r.stdout)
    body = "\n".join(l for l in body.splitlines()
                      if not l.startswith("# "))
    if args.func not in body:
        sys.exit(f"{args.func} is not in the preprocessed source -- it is "
                 f"still INCLUDE_ASM, so there is nothing to permute yet")
    (d / "base.c").write_text(body)

    shutil.copy(target_o, d / "target.o")

    if nm:
        tgt = {l.split()[-1] for l in
               subprocess.run([nm, str(target_o)], capture_output=True,
                              text=True).stdout.splitlines()
               if l.strip() and " T " in l and "NON_MATCHING" not in l}
        want = {m for m in re.findall(r"\bfunc_[0-9A-Fa-f]{8}\b", body)}
        missing = sorted(t for t in tgt if t not in want)
        if missing:
            print(f"warning: {len(missing)} function(s) are in target.o but "
                  f"not in base.c;\n         the permuter score will be "
                  f"inflated and will not converge.\n         first few: "
                  f"{missing[:4]}")

    sh = d / "compile.sh"
    sh.write_text(COMPILE_SH.format(
        cpp=cpp, cc1=cc1, as_=as_,
        cpp_flags="-D__GNUC__=2 "
                  f"-I{ROOT}/include -I{ROOT}/include/sdk",
        cc1_flags="-O2 -G0 -mcpu=r5900 -mips3 -fno-common -funsigned-char "
                  "-fno-strict-aliasing -mno-check-zero-division "
                  "-falign-functions=2 -quiet",
        as_flags=f"-EL -march=r5900 -mabi=eabi -G0 -no-pad-sections "
                 f"-I{ROOT}/include -I{ROOT}"))
    sh.chmod(0o755)

    (d / "settings.toml").write_text(
        f'func_name = "{args.func}"\n'
        f'compiler_type = "gcc"\n')

    print(f"wrote {d}")
    for f in ("base.c", "target.o", "compile.sh", "settings.toml"):
        print(f"  {f}")
    print(f"\n  python3 tools/decomp-permuter/permuter.py "
          f"{d.relative_to(ROOT)}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
