#!/usr/bin/env python3
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
ADDR_RE = re.compile(r"^func_([0-9A-Fa-f]{8})\.s$")

MACRO_INC = "include/macro.inc"

def main():
    if len(sys.argv) != 3:
        sys.exit("usage: mktarget.py <unit> <output.s>")
    unit, out = sys.argv[1], Path(sys.argv[2])

    d = ROOT / "asm" / "nonmatchings" / unit
    if not d.is_dir():
        sys.exit(f"{d} missing -- is '{unit}' a `c` subsegment, and split?")

    files = []
    for p in d.iterdir():
        m = ADDR_RE.match(p.name)
        if m:
            files.append((int(m.group(1), 16), p))
    if not files:
        sys.exit(f"no func_*.s under {d}")
    files.sort()

    lines = [f"/* Generated by tools/mktarget.py for {unit} -- do not edit */",
             f'.include "{MACRO_INC}"',
             ".section .text"]
    for _, p in files:
        lines.append(f'.include "{p.relative_to(ROOT).as_posix()}"')

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")
    print(f"{out}  ({len(files)} functions, "
          f"{files[0][0]:#010x}..{files[-1][0]:#010x})")


if __name__ == "__main__":
    main()
